In [1]:
import pandas as pd

Import data

In [1]:
hospice_df

NameError: name 'hospice_df' is not defined

In [2]:
hospice_df = pd.read_csv('data/'Hospice_General_Information.csv')
hospice_df.head(2)

SyntaxError: invalid syntax (<ipython-input-2-f5d3e3083838>, line 1)

In [3]:
hospice_df = pd.read_csv('data/'Hospice_General_Information.csv')
hospice_df.head(2)

SyntaxError: invalid syntax (<ipython-input-3-f5d3e3083838>, line 1)

In [4]:
hospice_df

NameError: name 'hospice_df' is not defined

In [6]:
hospice_df = pd.read_csv('data/'Hospice_General_Information.csv')
hospice_df.head(2)

SyntaxError: invalid syntax (<ipython-input-6-f5d3e3083838>, line 1)

In [7]:
import os
cwd = os.getcwd()
cwd

'/Users/meganvogel/vanderbilt-aspire-data-essentials'

In [13]:
os.chdir('/Users/meganvogel/vanderbilt-aspire-data-essentials/data')

In [14]:
hospice_df = pd.read_csv('Hospice_General_Information.csv')

In [15]:
import panda as pd

ModuleNotFoundError: No module named 'panda'

In [11]:
import pandas as pd

In [16]:
hospice_df.tail()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,PhoneNumber,CMS Region,Ownership Type,Certification Date
4638,921720,"COMFORTING CARE HOSPICE, INC",5924 E LOS ANGELES AVENUE SUITE L,NaN,SIMI VALLEY,CA,93063,Ventura,(805) 236-8644,9,For-Profit,11/16/2017
4639,921721,"BLESSED HOPE HOSPICE, INC","2619 S WATERMAN AVE, SUITE D",NaN,SAN BERNARDINO,CA,92408,San Bernardino,(909) 492-0055,9,For-Profit,09/26/2017
4640,921722,VISTA HOSPICE CARE INC,"550 WEST VISTA WAY, SUITE 310",NaN,VISTA,CA,92083,San Diego,(760) 407-6425,9,For-Profit,12/21/2017
4641,921723,"NORCAL HOSPICE, INC.","700 W. 6TH STREET, SUITE K-B",NaN,GILROY,CA,95020,Santa Clara,(408) 548-7994,9,For-Profit,01/10/2018
4642,921729,"AFFECTIVE HOSPICE CARE, INC","5050 PALO VERDE STREET, SUITE 208",NaN,MONTCLAIR,CA,91763,San Bernardino,(909) 000-0000,9,For-Profit,12/26/2017

In [17]:
hospice_df = hospice_df.loc[hospice_df.State == 'TN']
hospice_df.head(1)

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,PhoneNumber,CMS Region,Ownership Type,Certification Date
2889,441501,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NaN,NASHVILLE,TN,37203,Davidson,(615) 327-1085,4,Non-Profit,04/10/1984

In [18]:
#Keep only the **Facility Name**, **Address Line 1**, **City**, **State**, **County Name**, **CMS Region**, **Ownership Type**, and **Cerfification Date** columns. Make all column names lower case and without spaces. 
hospice_df.columns = ['ccn', 'facility', 'address','address2','city', 'state','zip','county','phone', 'region', 'owner_type', 'cert_date']
hospice_df.head(2)

,ccn,facility,address,address2,city,state,zip,county,phone,region,owner_type,cert_date
2889,441501,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NaN,NASHVILLE,TN,37203,Davidson,(615) 327-1085,4,Non-Profit,04/10/1984
2890,441502,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",NaN,MEMPHIS,TN,38134,Shelby,(901) 516-1600,4,Non-Profit,08/31/1984

In [20]:
cancer_df=pd.read_csv('data/cancer_deaths.csv', skiprows=4, nrows = 96)
cancer_df.head()

FileNotFoundError: File b'data/cancer_deaths.csv' does not exist

In [23]:
cancer_df = pd.read_csv('cancer_deaths.csv', skiprows=4, nrows = 96)
cancer_df.head ()

,County,FIPS,Met Healthy People Objective of 161.4?,"Age-Adjusted Death Rate - deaths per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend in Death Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,Tennessee,47999,No,185.4,184.0,186.8,13933,falling,-1.4,-1.5,-1.2
1,United States,0,No,163.5,163.3,163.7,586354,falling,-1.5,-1.6,-1.5
2,Trousdale County,47169,No,265.5,219.0,319.1,24,stable,0.0,-1.3,1.3
3,Scott County,47151,No,241.0,214.5,270.0,63,stable,-0.5,-1.1,0.1
4,Cheatham County,47021,No,239.6,217.8,263.0,97,stable,-0.6,-1.4,0.3

In [24]:
cancer_df.tail ()

,County,FIPS,Met Healthy People Objective of 161.4?,"Age-Adjusted Death Rate - deaths per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend in Death Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
91,Sumner County,47165,Yes,161.2,153.0,169.6,305,falling,-2.2,-3.6,-0.8
92,Van Buren County,47175,Yes,160.3,122.7,207.4,14,stable,-0.9,-2.4,0.6
93,Pickett County,47137,Yes,158.7,123.3,203.9,15,stable,-0.5,-1.8,0.9
94,Fayette County,47047,Yes,154.3,139.1,170.7,81,falling,-1.4,-2.2,-0.5
95,Williamson County,47187,Yes,127.2,119.8,134.9,239,falling,-3.8,-4.8,-2.9

In [25]:
cancer_df.shape

(96, 11)

In [26]:
cancer_df.columns = ['county', 'fips', 'obj_met_healthy','deathrate_age_adjusted','lower95_CI', 'upper95_CI','avg_annual_count','trend','5yr_trend', 'lower95_CI.1', 'upper95_CI.1']
cancer_df.head(4)

,county,fips,obj_met_healthy,deathrate_age_adjusted,lower95_CI,upper95_CI,avg_annual_count,trend,5yr_trend,lower95_CI.1,upper95_CI.1
0,Tennessee,47999,No,185.4,184.0,186.8,13933,falling,-1.4,-1.5,-1.2
1,United States,0,No,163.5,163.3,163.7,586354,falling,-1.5,-1.6,-1.5
2,Trousdale County,47169,No,265.5,219.0,319.1,24,stable,0.0,-1.3,1.3
3,Scott County,47151,No,241.0,214.5,270.0,63,stable,-0.5,-1.1,0.1

In [27]:
pop_df = pd.read_csv('PEP_2017_PEPAGESEX')
pop_df.head()

FileNotFoundError: File b'PEP_2017_PEPAGESEX' does not exist

In [28]:
pop_df = pd.read_csv('PEP_2017_PEPAGESEX.csv')
pop_df.head()

,GEO.id,GEO.id2,GEO.display-label,cen42010sex0_age999,cen42010sex1_age999,cen42010sex2_age999,est42010sex0_age999,est42010sex1_age999,est42010sex2_age999,est72010sex0_age999,...,est72014sex2_medage,est72015sex0_medage,est72015sex1_medage,est72015sex2_medage,est72016sex0_medage,est72016sex1_medage,est72016sex2_medage,est72017sex0_medage,est72017sex1_medage,est72017sex2_medage
0,Id,Id2,Geography,"April 1, 2010 - Census - Both Sexes; Total","April 1, 2010 - Census - Male; Total","April 1, 2010 - Census - Female; Total","April 1, 2010 - Estimates Base - Both Sexes; T...","April 1, 2010 - Estimates Base - Male; Total","April 1, 2010 - Estimates Base - Female; Total",Population Estimate (as of July 1) - 2010 - Bo...,...,Population Estimate (as of July 1) - 2014 - Fe...,Population Estimate (as of July 1) - 2015 - Bo...,Population Estimate (as of July 1) - 2015 - Ma...,Population Estimate (as of July 1) - 2015 - Fe...,Population Estimate (as of July 1) - 2016 - Bo...,Population Estimate (as of July 1) - 2016 - Ma...,Population Estimate (as of July 1) - 2016 - Fe...,Population Estimate (as of July 1) - 2017 - Bo...,Population Estimate (as of July 1) - 2017 - Ma...,Population Estimate (as of July 1) - 2017 - Fe...
1,0500000US47001,47001,"Anderson County, Tennessee",75129,36308,38821,75094,36288,38806,75112,...,44.8,43.3,41.4,44.8,43.3,41.5,45.1,43.2,41.2,45.0
2,0500000US47003,47003,"Bedford County, Tennessee",45058,22357,22701,45056,22356,22700,45086,...,38.4,37.2,35.9,38.5,37.5,36.2,38.8,37.5,36.2,38.9
3,0500000US47005,47005,"Benton County, Tennessee",16489,8073,8416,16491,8074,8417,16511,...,48.3,46.6,45.2,48.0,47.1,45.7,48.4,47.4,46.0,48.7
4,0500000US47007,47007,"Bledsoe County, Tennessee",12876,6964,5912,12872,6962,5910,12882,...,46.3,43.4,41.7,46.5,43.5,41.9,46.4,43.9,42.1,47.3

In [29]:
pop_df.tail()

,GEO.id,GEO.id2,GEO.display-label,cen42010sex0_age999,cen42010sex1_age999,cen42010sex2_age999,est42010sex0_age999,est42010sex1_age999,est42010sex2_age999,est72010sex0_age999,...,est72014sex2_medage,est72015sex0_medage,est72015sex1_medage,est72015sex2_medage,est72016sex0_medage,est72016sex1_medage,est72016sex2_medage,est72017sex0_medage,est72017sex1_medage,est72017sex2_medage
91,0500000US47181,47181,"Wayne County, Tennessee",17021,9402,7619,17027,9404,7623,16987,...,45.8,42.6,39.8,46.5,42.7,39.9,46.7,43.1,40.0,47.4
92,0500000US47183,47183,"Weakley County, Tennessee",35021,17159,17862,35015,17157,17858,35042,...,39.2,37.6,36.0,39.2,37.9,36.2,39.6,38.3,36.6,40.1
93,0500000US47185,47185,"White County, Tennessee",25841,12640,13201,25836,12637,13199,25821,...,44.0,42.7,41.0,44.2,42.8,41.2,44.3,42.8,41.3,44.4
94,0500000US47187,47187,"Williamson County, Tennessee",183182,89336,93846,183252,89371,93881,184130,...,39.7,39.0,38.2,39.7,39.0,38.3,39.7,39.0,38.3,39.7
95,0500000US47189,47189,"Wilson County, Tennessee",113993,55834,58159,114057,55863,58194,114677,...,41.1,40.2,39.2,41.1,40.0,39.0,40.9,39.9,39.0,40.8

In [30]:
pop_df.shape

(96, 993)

In [31]:
hospice_df.head(5)

,ccn,facility,address,address2,city,state,zip,county,phone,region,owner_type,cert_date
2889,441501,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NaN,NASHVILLE,TN,37203,Davidson,(615) 327-1085,4,Non-Profit,04/10/1984
2890,441502,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",NaN,MEMPHIS,TN,38134,Shelby,(901) 516-1600,4,Non-Profit,08/31/1984
2891,441504,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,NaN,CHATTANOOGA,TN,37416,Hamilton,(423) 892-4289,4,Non-Profit,06/30/1986
2892,441506,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,NaN,BARTLETT,TN,38134,Shelby,(901) 680-0378,4,For-Profit,02/09/1987
2893,441507,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,NaN,SPRINGFIELD,TN,37172,Robertson,(615) 384-9425,4,Other,07/13/1987

In [32]:
hospice_df.tail(5)

,ccn,facility,address,address2,city,state,zip,county,phone,region,owner_type,cert_date
2940,441598,ENCOMPASS HOSPICE OF TENNESSEE,828 ROYAL PARKWAY SUITE 113,NaN,NASHVILLE,TN,37214,Davidson,(615) 889-3357,4,For-Profit,06/16/2010
2941,441599,QUALITY HOSPICE,341 WEST CENTRAL AVENUE,NaN,JAMESTOWN,TN,38556,Fentress,(931) 879-9330,4,For-Profit,01/04/2013
2942,441600,HEARTH HOSPICE,1800A ROSSVILLE AVE SUITE 114,NaN,CHATTANOOGA,TN,37408,Hamilton,(423) 531-6555,4,For-Profit,03/22/2013
2943,441602,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",400 ROYAL PARKWAY,NaN,NASHVILLE,TN,37214,Davidson,(615) 231-7113,4,Other,01/05/2016
2944,441603,KINDRED HOSPICE,"430 STUART RD NE, STE 2",NaN,CLEVELAND,TN,37312,Bradley,(423) 458-6455,4,For-Profit,01/04/2017

In [33]:
hospice_df.shape

(56, 12)

In [35]:
hospice_df.drop(columns = 'ccn')

,facility,address,address2,city,state,zip,county,phone,region,owner_type,cert_date
2889,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NaN,NASHVILLE,TN,37203,Davidson,(615) 327-1085,4,Non-Profit,04/10/1984
2890,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",NaN,MEMPHIS,TN,38134,Shelby,(901) 516-1600,4,Non-Profit,08/31/1984
2891,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,NaN,CHATTANOOGA,TN,37416,Hamilton,(423) 892-4289,4,Non-Profit,06/30/1986
2892,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,NaN,BARTLETT,TN,38134,Shelby,(901) 680-0378,4,For-Profit,02/09/1987
2893,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,NaN,SPRINGFIELD,TN,37172,Robertson,(615) 384-9425,4,Other,07/13/1987
2894,HOSPICE OF CUMBERLAND COUNTY INC,30 EAST ADAMS STREET,NaN,CROSSVILLE,TN,38555,Cumberland,(931) 484-4748,4,Non-Profit,07/12/1988
2895,HIGHPOINT HOSPICE,575 EAST BLEDSOE STREET SUITE 9,NaN,GALLATIN,TN,37066,Sumner,(615) 532-8669,4,For-Profit,10/11/1988
2896,HOSPICE OF WEST TENNESSEE,1804 HWY 45 BYPASS DUFFY TOWERS SUITE 100,NaN,JACKSON,TN,38305,Madison,(731) 664-4220,4,Combination Government & Non-Profit,10/24/1988
2897,KINDRED HOSPICE,750 E SPRING ST STE B1,NaN,COOKEVILLE,TN,38501,Putnam,(931) 528-5133,4,For-Profit,11/28/1989
2898,TENNOVA HOSPICE-CLARKSVILLE,141 HATCHER LANE,NaN,CLARKSVILLE,TN,37040,Montgomery,(931) 552-9551,4,For-Profit,02/21/1991
2899,AMEDISYS HOSPICE AN ADVENTA COMPANY,"1420 DUTCH VALLEY ROAD, SUITE C",NaN,KNOXVILLE,TN,37918,Knox,(865) 689-7123,4,For-Profit,07/26/1991
2900,BLOUNT MEMORIAL HOSPITAL HOSPICE,1095 EAST LAMAR ALEXANDER PARKWAY,NaN,MARYVILLE,TN,37804,Blount,(865) 977-5702,4,Government,11/14/1991
2901,ASERACARE HOSPICE - NASHVILLE,"441 DONELSON PIKE, SUITE 400",NaN,NASHVILLE,TN,37214,Davidson,(615) 316-2243,4,For-Profit,03/19/1992
2902,SUNCREST HOSPICE,903 MAIN STREET,NaN,NEW TAZEWELL,TN,37825,Claiborne,(423) 626-4272,4,For-Profit,04/02/1993
2903,LINCOLN MEDICAL HOME HEALTH AND HOSPICE,1797 WILSON PARKWAY,NaN,FAYETTEVILLE,TN,37334,Lincoln,(931) 433-8088,4,Government,03/05/1993
2904,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",7205 LEE HIGHWAY SUITE B,NaN,CHATTANOOGA,TN,37421,Hamilton,(423) 499-0018,4,Other,05/19/1993
2905,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",1500 WEST ELK AVENUE SUITE 202,NaN,ELIZABETHTON,TN,37643,Carter,(423) 547-0852,4,For-Profit,06/30/1993
2906,BAPTIST TRINITY HOSPICE,6141 WALNUT GROVE ROAD,NaN,MEMPHIS,TN,38120,Shelby,(901) 767-6767,4,Other,08/30/1993
2907,MEDICAL CENTER HOSPICE,"509 MED TECH PARKWAY, SUITE 200",NaN,JOHNSON CITY,TN,37604,Washington,(423) 431-6146,4,Non-Profit,10/01/1993
2908,COVENANT HOSPICE,3001 LAKE BROOK BLVD SUITE 101,NaN,KNOXVILLE,TN,37909,Knox,(423) 374-0600,4,Non-Profit,11/15/1993
2909,AVALON HOSPICE,"2525 PERIMETER PLACE DRIVE, SUITE 105",NaN,NASHVILLE,TN,37214,Davidson,(615) 889-5995,4,For-Profit,06/20/1994
2910,UNIVERSITY OF TN MEDICAL CENTER HOME CARE SERV...,"4435 VALLEY VIEW DRIVE, SUITE 104",NaN,KNOXVILLE,TN,37917,Knox,(865) 544-6222,4,For-Profit,06/09/1994
2911,HENRY COUNTY MEDICAL CENTER HOSPICE,311 EAST WOOD STREET,NaN,PARIS,TN,38242,Henry,(731) 642-7600,4,Government,06/24/1994
2912,SMOKY MOUNTAIN HOSPICE INC,222 HERITAGE BLVD PO BOX 754,NaN,NEWPORT,TN,37821,Cocke,(423) 623-0233,4,For-Profit,06/23/1994
2913,GENTIVA HOSPICE,1400 DONELSON PIKE SUITE B5,NaN,NASHVILLE,TN,37217,Davidson,(615) 837-9556,4,For-Profit,06/30/1994
2914,WILLOWBROOK HOSPICE INC,1335 WEST MAIN STREET SUITE B,NaN,FRANKLIN,TN,37064,Williamson,(615) 791-8499,4,For-Profit,08/01/1994
2915,HOME HEALTH CARE OF EAST TENNESSEE INC AND HOS...,2765 EXECUTIVE PARK DRIVE,NaN,CLEVELAND,TN,37312,Bradley,(423) 479-4581,4,For-Profit,01/17/1995
2916,WELLMONT HOSPICE,280 STEELES ROAD,NaN,BRISTOL,TN,37620,Sullivan,(423) 844-5252,4,Non-Profit,01/12/1995
2917,TENNOVA HEALTHCARE HOSPICE,7447 ANDERSONVILLE PIKE,NaN,KNOXVILLE,TN,37938,Knox,(865) 925-5500,4,For-Profit,05/16/1995
2918,HOSPICE COMPASSUS,"1805 N JACKSON STREET, SUITE 11 & 12",NaN,TULLAHOMA,TN,37388,Coffee,(931) 455-9118,4,For-Profit,07/31/1996
2919,CROSSROADS HOSPICE OF TENNESSE,1669 SHELBY OAKS DRIVE SUITE 106,NaN,MEMPHIS,TN,38134,Shelby,(901) 382-9292,4,For-Profit,05/22/1998
2920,BAPTIST MEMORIAL HOME CARE & HOSPICE,631 R B WILSON DRIVE,NaN,HUNTINGDON,TN,38344,Carroll,(731) 986-3220,4,Non-Profit,07/29/1998
2921,AVALON HOSPICE,7625 HAMILTON PARK DRIVE SUITE 19,NaN,CHATTANOOGA,TN,37421,Hamilton,(423) 892-3737,4,For-Profit,09/16/1998
2922,BAPTIST HOMECARE AND HOSPICE,1201 BISHOP STREET,NaN,UNION CITY,TN,38261,Obion,(731) 884-8617,4,Non-Profit,05/27/1999
2923,UNIVERSITY OF TN MEDICAL CENTER HOSPICE SERV,"3301 WEST ANDREW JOHNSON HIGHWAY, SUITE 102",NaN,MORRISTOWN,TN,37814,Hamblen,(423) 586-7858,4,Other,07/14/1999
2924,COMPASSUS-MEMPHIS,5796 SHELBY OAKS DRIVE SUITE 6,NaN,MEMPHIS,TN,38134,Shelby,(901) 309-1855,4,For-Profit,11/06/2000
2925,ASERACARE HOSPICE - MCKENZIE,1939 A CEDAR STREET,NaN,MC KENZIE,TN,38201,Carroll,(731) 392-1340,4,For-Profit,06/04/2001
2926,TENNESSEE QUALITY HOSPICE,2879 HIGHWAY 45 BYPASS,NaN,JACKSON,TN,38305,Madison,(731) 410-2250,4,For-Profit,06/18/2001
2927,CARIS HEALTHCARE,242 HERITAGE PARK DRIVE SUITE 101,NaN,MURFREESBORO,TN,37129,Rutherford,(615) 217-8720,4,For-Profit,03/08/2004
2928,CARIS HEALTHCARE,10651 COWARD MILL RD SUITE B,NaN,KNOXVILLE,TN,37931,Knox,(865) 694-4848,4,For-Profit,03/25/2004
2929,CARIS HEALTHCARE,2525 PERIMETER PLACE DRIVE SUITE 131,NaN,NASHVILLE,TN,37214,Davidson,(615) 366-9952,4,For-Profit,06/01/2004
2930,CARIS HEALTHCARE,110 A WEST SPRINGBROOK DR STE A,NaN,JOHNSON CITY,TN,37604,Washington,(423) 929-2044,4,For-Profit,06/17/2004
2931,VOLUNTEER HOSPICE,211A DEXTER L WOODS MEMORIAL BLVD,NaN,WAYNESBORO,TN,38485,Wayne,(931) 722-9601,4,For-Profit,11/22/2004
2932,CARIS HEALTHCARE,5959 SHALLOWFORD ROAD SUITE 551,NaN,CHATTANOOGA,TN,37421,Hamilton,(423) 899-4044,4,For-Profit,05/12/2005
2933,"GUARDIAN HOSPICE OF NASHVILLE, LLC","741 COOL SPRINGS BOULEVARD, SUITE 102",NaN,FRANKLIN,TN,37067,Williamson,(615) 771-8979,4,For-Profit,06/01/2005
2934,ADORATION HOSPICE,545 MAINSTREAM DRIVE SUITE 412,NaN,NASHVILLE,TN,37228,Davidson,(615) 242-5936,4,For-Profit,12/02/2005
2935,CARIS HEALTHCARE,17410 HIGHWAY 64,NaN,SOMERVILLE,TN,38068,Fayette,(901) 465-2120,4,For-Profit,12/07/2005
2936,CARIS HEALTHCARE,2308A MEMORIAL BLVD,NaN,SPRINGFIELD,TN,37172,Robertson,(615) 384-3833,4,For-Profit,03/30/2006
2937,CARIS HEALTHCARE,"421 OLD RICEVILLE ROAD, SUITE 3",NaN,ATHENS,TN,37303,McMinn,(423) 507-0889,4,For-Profit,05/31/2006
2938,"UNITY HOSPICE CARE OF TENNESSEE, LLC",202 EAST SCHOOL STREET,NaN,LINDEN,TN,37096,Perry,(901) 756-7322,4,For-Profit,02/21/2007
2939,HANCOCK COUNTY HOME HEALTH & HOSPICE AGENCY,1246 MAIN STREET PO BOX 32,NaN,SNEEDVILLE,TN,37869,Hancock,(423) 733-4032,4,Government,04/21/2010
2940,ENCOMPASS HOSPICE OF TENNESSEE,828 ROYAL PARKWAY SUITE 113,NaN,NASHVILLE,TN,37214,Davidson,(615) 889-3357,4,For-Profit,06/16/2010
2941,QUALITY HOSPICE,341 WEST CENTRAL AVENUE,NaN,JAMESTOWN,TN,38556,Fentress,(931) 879-9330,4,For-Profit,01/04/2013
2942,HEARTH HOSPICE,1800A ROSSVILLE AVE SUITE 114,NaN,CHATTANOOGA,TN,37408,Hamilton,(423) 531-6555,4,For-Profit,03/22/2013
2943,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",400 ROYAL PARKWAY,NaN,NASHVILLE,TN,37214,Davidson,(615) 231-7113,4,Other,01/05/2016
2944,KINDRED HOSPICE,"430 STUART RD NE, STE 2",NaN,CLEVELAND,TN,37312,Bradley,(423) 458-6455,4,For-Profit,01/04/2017

In [36]:
hospice_df.drop(columns = 'address2','zip','phone')

SyntaxError: positional argument follows keyword argument (<ipython-input-36-0140db342ab7>, line 1)

In [40]:
hospice_df.drop(columns = ['ccn','address2','zip','phone'])

,facility,address,city,state,county,region,owner_type,cert_date
2889,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NASHVILLE,TN,Davidson,4,Non-Profit,04/10/1984
2890,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",MEMPHIS,TN,Shelby,4,Non-Profit,08/31/1984
2891,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,CHATTANOOGA,TN,Hamilton,4,Non-Profit,06/30/1986
2892,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,BARTLETT,TN,Shelby,4,For-Profit,02/09/1987
2893,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,SPRINGFIELD,TN,Robertson,4,Other,07/13/1987
2894,HOSPICE OF CUMBERLAND COUNTY INC,30 EAST ADAMS STREET,CROSSVILLE,TN,Cumberland,4,Non-Profit,07/12/1988
2895,HIGHPOINT HOSPICE,575 EAST BLEDSOE STREET SUITE 9,GALLATIN,TN,Sumner,4,For-Profit,10/11/1988
2896,HOSPICE OF WEST TENNESSEE,1804 HWY 45 BYPASS DUFFY TOWERS SUITE 100,JACKSON,TN,Madison,4,Combination Government & Non-Profit,10/24/1988
2897,KINDRED HOSPICE,750 E SPRING ST STE B1,COOKEVILLE,TN,Putnam,4,For-Profit,11/28/1989
2898,TENNOVA HOSPICE-CLARKSVILLE,141 HATCHER LANE,CLARKSVILLE,TN,Montgomery,4,For-Profit,02/21/1991
2899,AMEDISYS HOSPICE AN ADVENTA COMPANY,"1420 DUTCH VALLEY ROAD, SUITE C",KNOXVILLE,TN,Knox,4,For-Profit,07/26/1991
2900,BLOUNT MEMORIAL HOSPITAL HOSPICE,1095 EAST LAMAR ALEXANDER PARKWAY,MARYVILLE,TN,Blount,4,Government,11/14/1991
2901,ASERACARE HOSPICE - NASHVILLE,"441 DONELSON PIKE, SUITE 400",NASHVILLE,TN,Davidson,4,For-Profit,03/19/1992
2902,SUNCREST HOSPICE,903 MAIN STREET,NEW TAZEWELL,TN,Claiborne,4,For-Profit,04/02/1993
2903,LINCOLN MEDICAL HOME HEALTH AND HOSPICE,1797 WILSON PARKWAY,FAYETTEVILLE,TN,Lincoln,4,Government,03/05/1993
2904,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",7205 LEE HIGHWAY SUITE B,CHATTANOOGA,TN,Hamilton,4,Other,05/19/1993
2905,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",1500 WEST ELK AVENUE SUITE 202,ELIZABETHTON,TN,Carter,4,For-Profit,06/30/1993
2906,BAPTIST TRINITY HOSPICE,6141 WALNUT GROVE ROAD,MEMPHIS,TN,Shelby,4,Other,08/30/1993
2907,MEDICAL CENTER HOSPICE,"509 MED TECH PARKWAY, SUITE 200",JOHNSON CITY,TN,Washington,4,Non-Profit,10/01/1993
2908,COVENANT HOSPICE,3001 LAKE BROOK BLVD SUITE 101,KNOXVILLE,TN,Knox,4,Non-Profit,11/15/1993
2909,AVALON HOSPICE,"2525 PERIMETER PLACE DRIVE, SUITE 105",NASHVILLE,TN,Davidson,4,For-Profit,06/20/1994
2910,UNIVERSITY OF TN MEDICAL CENTER HOME CARE SERV...,"4435 VALLEY VIEW DRIVE, SUITE 104",KNOXVILLE,TN,Knox,4,For-Profit,06/09/1994
2911,HENRY COUNTY MEDICAL CENTER HOSPICE,311 EAST WOOD STREET,PARIS,TN,Henry,4,Government,06/24/1994
2912,SMOKY MOUNTAIN HOSPICE INC,222 HERITAGE BLVD PO BOX 754,NEWPORT,TN,Cocke,4,For-Profit,06/23/1994
2913,GENTIVA HOSPICE,1400 DONELSON PIKE SUITE B5,NASHVILLE,TN,Davidson,4,For-Profit,06/30/1994
2914,WILLOWBROOK HOSPICE INC,1335 WEST MAIN STREET SUITE B,FRANKLIN,TN,Williamson,4,For-Profit,08/01/1994
2915,HOME HEALTH CARE OF EAST TENNESSEE INC AND HOS...,2765 EXECUTIVE PARK DRIVE,CLEVELAND,TN,Bradley,4,For-Profit,01/17/1995
2916,WELLMONT HOSPICE,280 STEELES ROAD,BRISTOL,TN,Sullivan,4,Non-Profit,01/12/1995
2917,TENNOVA HEALTHCARE HOSPICE,7447 ANDERSONVILLE PIKE,KNOXVILLE,TN,Knox,4,For-Profit,05/16/1995
2918,HOSPICE COMPASSUS,"1805 N JACKSON STREET, SUITE 11 & 12",TULLAHOMA,TN,Coffee,4,For-Profit,07/31/1996
2919,CROSSROADS HOSPICE OF TENNESSE,1669 SHELBY OAKS DRIVE SUITE 106,MEMPHIS,TN,Shelby,4,For-Profit,05/22/1998
2920,BAPTIST MEMORIAL HOME CARE & HOSPICE,631 R B WILSON DRIVE,HUNTINGDON,TN,Carroll,4,Non-Profit,07/29/1998
2921,AVALON HOSPICE,7625 HAMILTON PARK DRIVE SUITE 19,CHATTANOOGA,TN,Hamilton,4,For-Profit,09/16/1998
2922,BAPTIST HOMECARE AND HOSPICE,1201 BISHOP STREET,UNION CITY,TN,Obion,4,Non-Profit,05/27/1999
2923,UNIVERSITY OF TN MEDICAL CENTER HOSPICE SERV,"3301 WEST ANDREW JOHNSON HIGHWAY, SUITE 102",MORRISTOWN,TN,Hamblen,4,Other,07/14/1999
2924,COMPASSUS-MEMPHIS,5796 SHELBY OAKS DRIVE SUITE 6,MEMPHIS,TN,Shelby,4,For-Profit,11/06/2000
2925,ASERACARE HOSPICE - MCKENZIE,1939 A CEDAR STREET,MC KENZIE,TN,Carroll,4,For-Profit,06/04/2001
2926,TENNESSEE QUALITY HOSPICE,2879 HIGHWAY 45 BYPASS,JACKSON,TN,Madison,4,For-Profit,06/18/2001
2927,CARIS HEALTHCARE,242 HERITAGE PARK DRIVE SUITE 101,MURFREESBORO,TN,Rutherford,4,For-Profit,03/08/2004
2928,CARIS HEALTHCARE,10651 COWARD MILL RD SUITE B,KNOXVILLE,TN,Knox,4,For-Profit,03/25/2004
2929,CARIS HEALTHCARE,2525 PERIMETER PLACE DRIVE SUITE 131,NASHVILLE,TN,Davidson,4,For-Profit,06/01/2004
2930,CARIS HEALTHCARE,110 A WEST SPRINGBROOK DR STE A,JOHNSON CITY,TN,Washington,4,For-Profit,06/17/2004
2931,VOLUNTEER HOSPICE,211A DEXTER L WOODS MEMORIAL BLVD,WAYNESBORO,TN,Wayne,4,For-Profit,11/22/2004
2932,CARIS HEALTHCARE,5959 SHALLOWFORD ROAD SUITE 551,CHATTANOOGA,TN,Hamilton,4,For-Profit,05/12/2005
2933,"GUARDIAN HOSPICE OF NASHVILLE, LLC","741 COOL SPRINGS BOULEVARD, SUITE 102",FRANKLIN,TN,Williamson,4,For-Profit,06/01/2005
2934,ADORATION HOSPICE,545 MAINSTREAM DRIVE SUITE 412,NASHVILLE,TN,Davidson,4,For-Profit,12/02/2005
2935,CARIS HEALTHCARE,17410 HIGHWAY 64,SOMERVILLE,TN,Fayette,4,For-Profit,12/07/2005
2936,CARIS HEALTHCARE,2308A MEMORIAL BLVD,SPRINGFIELD,TN,Robertson,4,For-Profit,03/30/2006
2937,CARIS HEALTHCARE,"421 OLD RICEVILLE ROAD, SUITE 3",ATHENS,TN,McMinn,4,For-Profit,05/31/2006
2938,"UNITY HOSPICE CARE OF TENNESSEE, LLC",202 EAST SCHOOL STREET,LINDEN,TN,Perry,4,For-Profit,02/21/2007
2939,HANCOCK COUNTY HOME HEALTH & HOSPICE AGENCY,1246 MAIN STREET PO BOX 32,SNEEDVILLE,TN,Hancock,4,Government,04/21/2010
2940,ENCOMPASS HOSPICE OF TENNESSEE,828 ROYAL PARKWAY SUITE 113,NASHVILLE,TN,Davidson,4,For-Profit,06/16/2010
2941,QUALITY HOSPICE,341 WEST CENTRAL AVENUE,JAMESTOWN,TN,Fentress,4,For-Profit,01/04/2013
2942,HEARTH HOSPICE,1800A ROSSVILLE AVE SUITE 114,CHATTANOOGA,TN,Hamilton,4,For-Profit,03/22/2013
2943,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",400 ROYAL PARKWAY,NASHVILLE,TN,Davidson,4,Other,01/05/2016
2944,KINDRED HOSPICE,"430 STUART RD NE, STE 2",CLEVELAND,TN,Bradley,4,For-Profit,01/04/2017

In [41]:
hospice_df.shape

(56, 12)

In [42]:
pop_df.head()

,GEO.id,GEO.id2,GEO.display-label,cen42010sex0_age999,cen42010sex1_age999,cen42010sex2_age999,est42010sex0_age999,est42010sex1_age999,est42010sex2_age999,est72010sex0_age999,...,est72014sex2_medage,est72015sex0_medage,est72015sex1_medage,est72015sex2_medage,est72016sex0_medage,est72016sex1_medage,est72016sex2_medage,est72017sex0_medage,est72017sex1_medage,est72017sex2_medage
0,Id,Id2,Geography,"April 1, 2010 - Census - Both Sexes; Total","April 1, 2010 - Census - Male; Total","April 1, 2010 - Census - Female; Total","April 1, 2010 - Estimates Base - Both Sexes; T...","April 1, 2010 - Estimates Base - Male; Total","April 1, 2010 - Estimates Base - Female; Total",Population Estimate (as of July 1) - 2010 - Bo...,...,Population Estimate (as of July 1) - 2014 - Fe...,Population Estimate (as of July 1) - 2015 - Bo...,Population Estimate (as of July 1) - 2015 - Ma...,Population Estimate (as of July 1) - 2015 - Fe...,Population Estimate (as of July 1) - 2016 - Bo...,Population Estimate (as of July 1) - 2016 - Ma...,Population Estimate (as of July 1) - 2016 - Fe...,Population Estimate (as of July 1) - 2017 - Bo...,Population Estimate (as of July 1) - 2017 - Ma...,Population Estimate (as of July 1) - 2017 - Fe...
1,0500000US47001,47001,"Anderson County, Tennessee",75129,36308,38821,75094,36288,38806,75112,...,44.8,43.3,41.4,44.8,43.3,41.5,45.1,43.2,41.2,45.0
2,0500000US47003,47003,"Bedford County, Tennessee",45058,22357,22701,45056,22356,22700,45086,...,38.4,37.2,35.9,38.5,37.5,36.2,38.8,37.5,36.2,38.9
3,0500000US47005,47005,"Benton County, Tennessee",16489,8073,8416,16491,8074,8417,16511,...,48.3,46.6,45.2,48.0,47.1,45.7,48.4,47.4,46.0,48.7
4,0500000US47007,47007,"Bledsoe County, Tennessee",12876,6964,5912,12872,6962,5910,12882,...,46.3,43.4,41.7,46.5,43.5,41.9,46.4,43.9,42.1,47.3

In [43]:
pop_df.shape

(96, 993)

In [48]:
pop_df_noapril = pop_df.drop(columns = ['cen42010sex0_age999','cen42010sex1_age999','cen42010sex2_age999','est42010sex0_age999','est42010sex1_age999','est42010sex2_age999'])

In [46]:
pop_df.shape

(96, 993)

In [49]:
pop_df.drop(columns = ['cen42010sex0_age999','cen42010sex1_age999','cen42010sex2_age999','est42010sex0_age999','est42010sex1_age999','est42010sex2_age999'])
pop_df.shape

(96, 993)

In [54]:
pop_df1 = pop_df[pop_df.columns.drop(list(pop_df.filter(regex='est4')))]
pop_df1.shape

(96, 894)

In [58]:
pop_df2 = pop_df1[pop_df1.columns.drop(list(pop_df1.filter(regex = '2011')))]
pop_df3 = pop_df2[pop_df2.columns.drop(list(pop_df2.filter(regex = '2012')))]
pop_df4 = pop_df3[pop_df3.columns.drop(list(pop_df3.filter(regex = '2013')))]
pop_df5 = pop_df4[pop_df4.columns.drop(list(pop_df4.filter(regex = '2015')))]
pop_df6 = pop_df5[pop_df5.columns.drop(list(pop_df5.filter(regex = '2016')))]
pop_df6.shape

(96, 399)

In [59]:
git push

SyntaxError: invalid syntax (<ipython-input-59-83a80d2515aa>, line 1)